Update eslint-plugin-import config
fargito/serverless-monorepo-microservices-template pull request #52
Opened 2022-01-21 15:38 UTC by adriencaccia

2022-01-21 17:56 UTC, fargito approved these changes
LGTM

2022-01-21 22:03 UTC, fargito requested changes
There may be a problem with the tests in frontend/app, @adriencaccia can you check ?

![image](https://user-images.githubusercontent.com/29537204/150606499-c3e66eb8-e0b8-4bb8-90ab-633a827fe731.png)

2022-01-24 09:22 UTC, adriencaccia commented
It should be good now !

2022-01-24 09:38 UTC, fargito approved these changes
Okpm

2022-01-24 09:41 UTC, merged